-- Seed portfolio projects
INSERT INTO portfolio_projects (
  title, slug, description, category, featured_image, client_name, project_url, case_study_url,
  results_metric_1_label, results_metric_1_value, results_metric_2_label, results_metric_2_value,
  technologies, featured, published
) VALUES
(
  'Luxe Fashion Boutique',
  'luxe-fashion-boutique',
  'Complete e-commerce redesign for a high-end fashion retailer. We focused on creating an elegant shopping experience that showcases their premium products while optimizing for conversions.',
  'E-commerce',
  '/placeholder.svg?height=600&width=800',
  'Jessica Martinez',
  'https://luxefashion.example.com',
  '/portfolio/luxe-fashion-case-study',
  'Increase in Sales',
  '340%',
  'Higher Conversion Rate',
  '65%',
  ARRAY['Next.js', 'Shopify', 'Tailwind CSS', 'Stripe'],
  true,
  true
),
(
  'TechStart SaaS Platform',
  'techstart-saas-platform',
  'Landing page and dashboard design for a B2B SaaS startup. We created a conversion-focused landing page that clearly communicates value and drives sign-ups.',
  'SaaS',
  '/placeholder.svg?height=600&width=800',
  'Michael Chen',
  'https://techstart.example.com',
  '/portfolio/techstart-case-study',
  'More Sign-ups',
  '250%',
  'Lower Bounce Rate',
  '45%',
  ARRAY['React', 'Node.js', 'PostgreSQL', 'AWS'],
  true,
  true
),
(
  'Bella Vista Restaurant Chain',
  'bella-vista-restaurant-chain',
  'Multi-location restaurant website with online ordering system. We created an appetizing design that showcases their cuisine and makes ordering effortless.',
  'Restaurant',
  '/placeholder.svg?height=600&width=800',
  'Roberto Silva',
  'https://bellavista.example.com',
  '/portfolio/bella-vista-case-study',
  'More Online Orders',
  '200%',
  'Mobile Traffic Increase',
  '80%',
  ARRAY['WordPress', 'WooCommerce', 'Square API'],
  true,
  true
),
(
  'MedConnect Platform',
  'medconnect-platform',
  'Telemedicine platform connecting patients with healthcare providers',
  'HealthTech',
  '/placeholder.svg?height=300&width=400',
  'Dr. Sarah Johnson',
  'https://medconnect.example.com',
  '/portfolio/medconnect-case-study',
  'User Growth',
  '180%',
  'Patient Satisfaction',
  '95%',
  ARRAY['React', 'Node.js', 'Socket.io', 'HIPAA Compliance'],
  false,
  true
),
(
  'Prime Properties',
  'prime-properties',
  'Luxury real estate agency with advanced property search',
  'Real Estate',
  '/placeholder.svg?height=300&width=400',
  'David Park',
  'https://primeproperties.example.com',
  '/portfolio/prime-properties-case-study',
  'More Leads',
  '120%',
  'Faster Load Time',
  '60%',
  ARRAY['Next.js', 'Mapbox', 'Prisma', 'Vercel'],
  false,
  true
),
(
  'FitTrack App',
  'fittrack-app',
  'Mobile fitness app with personalized workout plans',
  'Fitness',
  '/placeholder.svg?height=300&width=400',
  'Emma Thompson',
  'https://fittrack.example.com',
  '/portfolio/fittrack-case-study',
  'App Downloads',
  '300%',
  'User Retention',
  '85%',
  ARRAY['React Native', 'Firebase', 'Stripe', 'HealthKit'],
  false,
  true
);
